spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_service
    password: 1
    username: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
  liquibase:
    enabled: false
    change-log: changelog/changelog.xml
    liquibase-schema: migration
    default-schema: wallet_service
  application:
    name: wallet-service
  jwt:
    secret-key: f9c9f2c74e849e48aac676442f8eaa67fbc13f62999f8d30ae9417518bd38456